### PR TITLE
fixed memo removal - issue #32

### PR DESCRIPTION
**Pull request by poliha**
Fixed removal of memo if a memo is entered before account ID.
**Fix**: Simple check if the memoValue is already set before hiding the memo

### CODE REVIEW

**Comment by bartekn** [comment]
Why not check the condition inside `hideMemo` method? Then there will be no code duplicates.

**Comment by poliha** [comment]
Yes I did think about doing this, but if for example the user had entered a memo and for whatever reason,  decides to cancel it by clicking on "cancel", it won't cancel unless the user erases the content of the memo field first. I could probably still explore ways to get it done inside `hideMemo` but I felt this handles the more specific case of when an account ID or stellar address is entered.

**Comment by bartekn** [comment]
OK, I checked the flow with more testing this time. `hideMemo` method is called from 3 places:
* `loadDestination.resetState` which is called:
  * When `destinationAddress` is empty (user removed the contents of `To` field): in this case we want to leave memo as it is so we can simply remove this call to `hideMemo`.
  * When `FederationServer.resolve` fails and this can happen when:
    * `To` field is account ID and is wrong: maybe user haven't copied the full ID? We shouldn't remove the memo user entered.
    * `To` field is stellar address (like `bartek*stellar.org`) and is invalid or network call to federation server failed. In both cases we shouldn't remove the memo user entered.
* `FederationServer.resolve` callback in `loadDestination` when `To` field was account ID or stellar address that resolved to account ID without memo. I think that in this case we also shouldn't remove memo because user may have entered memo before filling `To` field (this is the case explained in #32).
* Template, when user clicks `cancel` button near memo. We can't remove this because we want to allow users to remove memo.

So I think that we can completely remove all calls to `hideMemo` in the controller. The only difference between removing `hideMemo` calls and the code in this PR is the following flow:
1. User clicks "Add memo" but leaves value field empty.
2. User fills "To" field.
3. Now:
  * Code in this PR would remove Memo box.
  * Removing `hideMemo` would leave Memo box. (I think this is preferred behaviour)

Let me know what you think. Sorry for a long write-up but I think we should keep the code as simple as possible.

**Comment by poliha** [comment]
Yes this sounds fine to me.
So essentially we only remove Memo when the user explicitly wants the memo to be removed.
This still works fine when a Memo is retrieved from a valid `FederationServer.resolve` call.
Sounds good will make the changes

**Pull request merged**
