### PR TITLE
Federation

### PR DESCRIPTION
**Pull request by bartekn**
# For Account ID:

zrzut ekranu 2016-02-10 o 18 45 17
# For Stellar address (no memo):

zrzut ekranu 2016-02-10 o 18 46 53
# For Stellar address (with memo):

zrzut ekranu 2016-02-10 o 18 47 37

Close https://github.com/stellar/account-viewer/issues/20

### CODE REVIEW

**Comment by irisli** [comment]
What does "You can't change the memo because it is part of this Stellar address." mean?

**Comment by bartekn** [comment]
It means that federation [returned memo](https://www.stellar.org/developers/learn/concepts/federation.html#federation-response). So we shouldn't allow a user to change it because changing it will make this payment to be delivered to a different user (or any user).

I'm happy to change this copy.

**Comment by irisli** [comment]
I've left styling and copy changes to your `federation` branch.

:+1: on styles and presentation and assuming it works

**Comment by bartekn** [comment]
Thanks @irisli! Looks much better now.

**Pull request merged**
