### PR TITLE
Hide payments smaller than 0.01 XLM by default.

### PR DESCRIPTION
**Pull request by fnando**
I'm hiding payments smaller than 0.01 XLM by default now. This will help with the spam problem.

animation

### CODE REVIEW

**Comment by jedmccaleb** [comment]
I like this better than the memo behind an icon

**Comment by fnando** [comment]
@jedmccaleb me too!

**Comment by bartekn** [comment]
It won't solve the phishing problem (some people will still follow the links in the memos). I think #55 is better.

**Comment by fnando** [comment]
Can we merge both PRs? I think they're complementary. Or least one of them.

**Comment by tomerweller** [comment]
Merged. Thanks!

**Pull request merged**
